import "./globals.css";
import Head from "next/head";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";

export const metadata = {
    title: "Password random generator",
    description: "Generated by create next app",
};
<Head>
    <link rel="icon" href="/favicon/favicon.ico" />
</Head>;
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ThemeRegistry>{children}</ThemeRegistry>
            </body>
        </html>
    );
}
